version: "3"
services:
  event_scanner:
    container_name: event_scanner
    image: timdaub/challenge-services
    depends_on:
      - redis
    logging:
        driver: awslogs
        options:
          awslogs-region: eu-central-1
          awslogs-group: challenge-services/event_scanner
          awslogs-stream-prefix: event_scanner_logs
  redis:
    container_name: redis
    image: redis
    volumes:
      - /data
    command: ["sh", "-c", "redis-server --appendonly \"yes\""]
    logging:
        driver: awslogs
        options:
          awslogs-region: eu-central-1
          awslogs-group: challenge-services/redis
          awslogs-stream-prefix: redis_logs
