version: "3.1"
services:
  event_scanner:
    container_name: event_scanner
    build: .
    depends_on:
      - redis
    volumes:
      - ./config/index.json:/usr/src/event-scanner/config/index.json
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis:/data
    command: ["sh", "-c", "redis-server --appendonly \"yes\""]
